/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfesseurRouteImport } from './routes/professeur'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfesseurIndexRouteImport } from './routes/professeur.index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfesseurRevenusRouteImport } from './routes/professeur.revenus'
import { Route as ProfesseurNouveauRouteImport } from './routes/professeur.nouveau'
import { Route as PlatformProfesseursRouteImport } from './routes/platform.professeurs'
import { Route as PlatformPartenariatsRouteImport } from './routes/platform.partenariats'
import { Route as PlatformParametresRouteImport } from './routes/platform.parametres'
import { Route as PlatformEtablissementsRouteImport } from './routes/platform.etablissements'
import { Route as PlatformCoursRouteImport } from './routes/platform.cours'
import { Route as PlatformAdminsRouteImport } from './routes/platform.admins'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppGradesRouteImport } from './routes/app.grades'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppEmploiRouteImport } from './routes/app.emploi'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AdminFilieresRouteImport } from './routes/admin.filieres'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminNiveauNiveauIdRouteImport } from './routes/admin.niveau.$niveauId'

const ProfesseurRoute = ProfesseurRouteImport.update({
  id: '/professeur',
  path: '/professeur',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseurIndexRoute = ProfesseurIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfesseurRoute,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfesseurRevenusRoute = ProfesseurRevenusRouteImport.update({
  id: '/revenus',
  path: '/revenus',
  getParentRoute: () => ProfesseurRoute,
} as any)
const ProfesseurNouveauRoute = ProfesseurNouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => ProfesseurRoute,
} as any)
const PlatformProfesseursRoute = PlatformProfesseursRouteImport.update({
  id: '/professeurs',
  path: '/professeurs',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPartenariatsRoute = PlatformPartenariatsRouteImport.update({
  id: '/partenariats',
  path: '/partenariats',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformParametresRoute = PlatformParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformEtablissementsRoute = PlatformEtablissementsRouteImport.update({
  id: '/etablissements',
  path: '/etablissements',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformCoursRoute = PlatformCoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAdminsRoute = PlatformAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => PlatformRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppEmploiRoute = AppEmploiRouteImport.update({
  id: '/emploi',
  path: '/emploi',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AdminFilieresRoute = AdminFilieresRouteImport.update({
  id: '/filieres',
  path: '/filieres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNiveauNiveauIdRoute = AdminNiveauNiveauIdRouteImport.update({
  id: '/niveau/$niveauId',
  path: '/niveau/$niveauId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/professeur': typeof ProfesseurRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/filieres': typeof AdminFilieresRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/emploi': typeof AppEmploiRoute
  '/app/events': typeof AppEventsRoute
  '/app/grades': typeof AppGradesRoute
  '/app/profile': typeof AppProfileRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/cours': typeof PlatformCoursRoute
  '/platform/etablissements': typeof PlatformEtablissementsRoute
  '/platform/parametres': typeof PlatformParametresRoute
  '/platform/partenariats': typeof PlatformPartenariatsRoute
  '/platform/professeurs': typeof PlatformProfesseursRoute
  '/professeur/nouveau': typeof ProfesseurNouveauRoute
  '/professeur/revenus': typeof ProfesseurRevenusRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/professeur/': typeof ProfesseurIndexRoute
  '/admin/niveau/$niveauId': typeof AdminNiveauNiveauIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/filieres': typeof AdminFilieresRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/emploi': typeof AppEmploiRoute
  '/app/events': typeof AppEventsRoute
  '/app/grades': typeof AppGradesRoute
  '/app/profile': typeof AppProfileRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/cours': typeof PlatformCoursRoute
  '/platform/etablissements': typeof PlatformEtablissementsRoute
  '/platform/parametres': typeof PlatformParametresRoute
  '/platform/partenariats': typeof PlatformPartenariatsRoute
  '/platform/professeurs': typeof PlatformProfesseursRoute
  '/professeur/nouveau': typeof ProfesseurNouveauRoute
  '/professeur/revenus': typeof ProfesseurRevenusRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/platform': typeof PlatformIndexRoute
  '/professeur': typeof ProfesseurIndexRoute
  '/admin/niveau/$niveauId': typeof AdminNiveauNiveauIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/platform': typeof PlatformRouteWithChildren
  '/professeur': typeof ProfesseurRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/filieres': typeof AdminFilieresRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/emploi': typeof AppEmploiRoute
  '/app/events': typeof AppEventsRoute
  '/app/grades': typeof AppGradesRoute
  '/app/profile': typeof AppProfileRoute
  '/platform/admins': typeof PlatformAdminsRoute
  '/platform/cours': typeof PlatformCoursRoute
  '/platform/etablissements': typeof PlatformEtablissementsRoute
  '/platform/parametres': typeof PlatformParametresRoute
  '/platform/partenariats': typeof PlatformPartenariatsRoute
  '/platform/professeurs': typeof PlatformProfesseursRoute
  '/professeur/nouveau': typeof ProfesseurNouveauRoute
  '/professeur/revenus': typeof ProfesseurRevenusRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/platform/': typeof PlatformIndexRoute
  '/professeur/': typeof ProfesseurIndexRoute
  '/admin/niveau/$niveauId': typeof AdminNiveauNiveauIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/platform'
    | '/professeur'
    | '/admin/events'
    | '/admin/filieres'
    | '/app/announcements'
    | '/app/emploi'
    | '/app/events'
    | '/app/grades'
    | '/app/profile'
    | '/platform/admins'
    | '/platform/cours'
    | '/platform/etablissements'
    | '/platform/parametres'
    | '/platform/partenariats'
    | '/platform/professeurs'
    | '/professeur/nouveau'
    | '/professeur/revenus'
    | '/admin/'
    | '/app/'
    | '/platform/'
    | '/professeur/'
    | '/admin/niveau/$niveauId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/events'
    | '/admin/filieres'
    | '/app/announcements'
    | '/app/emploi'
    | '/app/events'
    | '/app/grades'
    | '/app/profile'
    | '/platform/admins'
    | '/platform/cours'
    | '/platform/etablissements'
    | '/platform/parametres'
    | '/platform/partenariats'
    | '/platform/professeurs'
    | '/professeur/nouveau'
    | '/professeur/revenus'
    | '/admin'
    | '/app'
    | '/platform'
    | '/professeur'
    | '/admin/niveau/$niveauId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/platform'
    | '/professeur'
    | '/admin/events'
    | '/admin/filieres'
    | '/app/announcements'
    | '/app/emploi'
    | '/app/events'
    | '/app/grades'
    | '/app/profile'
    | '/platform/admins'
    | '/platform/cours'
    | '/platform/etablissements'
    | '/platform/parametres'
    | '/platform/partenariats'
    | '/platform/professeurs'
    | '/professeur/nouveau'
    | '/professeur/revenus'
    | '/admin/'
    | '/app/'
    | '/platform/'
    | '/professeur/'
    | '/admin/niveau/$niveauId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  ProfesseurRoute: typeof ProfesseurRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professeur': {
      id: '/professeur'
      path: '/professeur'
      fullPath: '/professeur'
      preLoaderRoute: typeof ProfesseurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeur/': {
      id: '/professeur/'
      path: '/'
      fullPath: '/professeur/'
      preLoaderRoute: typeof ProfesseurIndexRouteImport
      parentRoute: typeof ProfesseurRoute
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/professeur/revenus': {
      id: '/professeur/revenus'
      path: '/revenus'
      fullPath: '/professeur/revenus'
      preLoaderRoute: typeof ProfesseurRevenusRouteImport
      parentRoute: typeof ProfesseurRoute
    }
    '/professeur/nouveau': {
      id: '/professeur/nouveau'
      path: '/nouveau'
      fullPath: '/professeur/nouveau'
      preLoaderRoute: typeof ProfesseurNouveauRouteImport
      parentRoute: typeof ProfesseurRoute
    }
    '/platform/professeurs': {
      id: '/platform/professeurs'
      path: '/professeurs'
      fullPath: '/platform/professeurs'
      preLoaderRoute: typeof PlatformProfesseursRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/partenariats': {
      id: '/platform/partenariats'
      path: '/partenariats'
      fullPath: '/platform/partenariats'
      preLoaderRoute: typeof PlatformPartenariatsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/parametres': {
      id: '/platform/parametres'
      path: '/parametres'
      fullPath: '/platform/parametres'
      preLoaderRoute: typeof PlatformParametresRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/etablissements': {
      id: '/platform/etablissements'
      path: '/etablissements'
      fullPath: '/platform/etablissements'
      preLoaderRoute: typeof PlatformEtablissementsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/cours': {
      id: '/platform/cours'
      path: '/cours'
      fullPath: '/platform/cours'
      preLoaderRoute: typeof PlatformCoursRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/admins': {
      id: '/platform/admins'
      path: '/admins'
      fullPath: '/platform/admins'
      preLoaderRoute: typeof PlatformAdminsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grades': {
      id: '/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/emploi': {
      id: '/app/emploi'
      path: '/emploi'
      fullPath: '/app/emploi'
      preLoaderRoute: typeof AppEmploiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/filieres': {
      id: '/admin/filieres'
      path: '/filieres'
      fullPath: '/admin/filieres'
      preLoaderRoute: typeof AdminFilieresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/niveau/$niveauId': {
      id: '/admin/niveau/$niveauId'
      path: '/niveau/$niveauId'
      fullPath: '/admin/niveau/$niveauId'
      preLoaderRoute: typeof AdminNiveauNiveauIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFilieresRoute: typeof AdminFilieresRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminNiveauNiveauIdRoute: typeof AdminNiveauNiveauIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRoute,
  AdminFilieresRoute: AdminFilieresRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminNiveauNiveauIdRoute: AdminNiveauNiveauIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppEmploiRoute: typeof AppEmploiRoute
  AppEventsRoute: typeof AppEventsRoute
  AppGradesRoute: typeof AppGradesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppEmploiRoute: AppEmploiRoute,
  AppEventsRoute: AppEventsRoute,
  AppGradesRoute: AppGradesRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PlatformRouteChildren {
  PlatformAdminsRoute: typeof PlatformAdminsRoute
  PlatformCoursRoute: typeof PlatformCoursRoute
  PlatformEtablissementsRoute: typeof PlatformEtablissementsRoute
  PlatformParametresRoute: typeof PlatformParametresRoute
  PlatformPartenariatsRoute: typeof PlatformPartenariatsRoute
  PlatformProfesseursRoute: typeof PlatformProfesseursRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAdminsRoute: PlatformAdminsRoute,
  PlatformCoursRoute: PlatformCoursRoute,
  PlatformEtablissementsRoute: PlatformEtablissementsRoute,
  PlatformParametresRoute: PlatformParametresRoute,
  PlatformPartenariatsRoute: PlatformPartenariatsRoute,
  PlatformProfesseursRoute: PlatformProfesseursRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface ProfesseurRouteChildren {
  ProfesseurNouveauRoute: typeof ProfesseurNouveauRoute
  ProfesseurRevenusRoute: typeof ProfesseurRevenusRoute
  ProfesseurIndexRoute: typeof ProfesseurIndexRoute
}

const ProfesseurRouteChildren: ProfesseurRouteChildren = {
  ProfesseurNouveauRoute: ProfesseurNouveauRoute,
  ProfesseurRevenusRoute: ProfesseurRevenusRoute,
  ProfesseurIndexRoute: ProfesseurIndexRoute,
}

const ProfesseurRouteWithChildren = ProfesseurRoute._addFileChildren(
  ProfesseurRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PlatformRoute: PlatformRouteWithChildren,
  ProfesseurRoute: ProfesseurRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
